### PR TITLE
Cross-publish to Scala 2.13

### PR DESCRIPTION
**Pull request by nightscape**
This PR gets rid of `scripted` for running tests and instead injects the plugin into the compiler in the test scope.
This allows cross-publishing to other versions as the one from SBT.

### CODE REVIEW

**Comment by takezoe** [comment]
Great thanks!

**Comment by nightscape** [comment]
Thanks for merging!
Would you mind creating a release with the 2.13 artifacts?

**Comment by takezoe** [comment]
Yup, I will do that later today.

**Comment by takezoe** [comment]
Released at sonatype. It will be available on Maven central shortly.

**Comment by nightscape** [comment]
Thanks! :smiley:

**Pull request merged**
